// A decorative, deterministic "QR-ish" pattern — good enough to
// visually represent a ticket QR code without pulling in a QR
// generation library. Swap for a real QR component once tickets
// are generated by a backend.
export default function QrPlaceholder({ size = 140 }) {
  const cells = 10;
  const cellSize = size / cells;

  // A fixed seed pattern (not random per render) so the "QR" looks
  // the same every time instead of flickering on re-render.
  const pattern = [
    1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
    0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
    1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
    1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
  ];

  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} aria-label="Ticket QR code">
      <rect width={size} height={size} fill="white" />
      {pattern.map((filled, i) => {
        if (!filled) return null;
        const x = (i % cells) * cellSize;
        const y = Math.floor(i / cells) * cellSize;
        return <rect key={i} x={x} y={y} width={cellSize} height={cellSize} fill="#101418" />;
      })}
    </svg>
  );
}
